dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable


install:
  - npm install

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

