dist: trusty

language: node_js
node_js:
  - "12"

addons:
  chrome: stable
  sudo: required
  
before_install:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo apt install ./google-chrome-stable_current_amd64.deb
  - google-chrome
  - cd frontend

script:
  - npm run test --browsers=ChromeHeadlessCI

after_script:
  - cat ../coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

