dist: trusty

language: node_js
node_js:
  # - "10"
  - "12"

addons:
  chrome: stable

# cache:
#   npm: false
  # directories:
  #   - "node_modules"
  
before_install:
  - cd frontend

# install:
  # - npm install
  # - npm i --save-dev @ionic/angular-toolkit@2.3.1
  # - npm i @angular-devkit/build-angular@0.803.24
  # - npm i @angular/cli@8.3.26

before_script:
  # - npm audit
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &

script:
  - npm run test -- --no-watch --code-coverage --reporters=coverage,coveralls --no-progress --browsers=ChromeHeadlessCI
  # - ng test "--no-watch" "--code-coverage" "--reporters=coverage,coveralls" "--no-progress" "--browsers=ChromeHeadlessCI"

after_script:
  - cat ../coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
