dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable
  
before_install:
  - cd frontend
  - echo 65536 | sudo tee -a /proc/sys/fs/inotify/max_user_watches

install:
  - npm install
  - npm i @angular-devkit/build-angular@0.803.24
  - npm i @angular/cli@8.3.26

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm run test -- --no-watch --code-coverage --reporters=coverage,coveralls --no-progress --browsers=ChromeHeadlessCI
  - cat ../coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js