dist: trusty

language: node_js
node_js:
  - "12"

addons:
  chrome: beta
  
before_install:
  - cd frontend

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &

script:
  - npm run test --browsers=ChromeHeadlessCI

after_script:
  - cat ../coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

