dist: trusty

language: node_js
node_js:
  - "12"

addons:
  chrome: stable
  
before_install:
  - sudo useradd -m user
  - su user
  - cd frontend

install:
  - npm install

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &

script:
  - npm run test -- --no-watch --code-coverage --reporters=coverage,coveralls --no-progress --browsers=ChromeHeadlessCI
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js