dist: trusty

language: node_js
node_js:
  - "12"

addons:
  chrome: stable
  sudo: required
  
before_install:
  - cd frontend
  
before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:9876 &

script:
  - npm run test --browsers=ChromeHeadlessCI

after_script:
  - cat ../coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

